###############################################################################
# Name:carbon-maps-api appEngine configuration
# Author: Kevin Peters
###############################################################################

runtime: nodejs16